### ISSUE TITLE
Doesn't support SRP auth

### ISSUE THREAD

**Issue by mattbradbury** [capless/warrant#1]

**Comment by bjinwright** [comment]
I've started working on this. https://github.com/bjinwright/pysrp

**Comment by mattbradbury** [comment]
Good luck, I've had trouble finding documentation from AWS on the specifics of how to format the response back.

If you've gotten an authentication to work ever in Python I would love to see how you did it

-Matt

**Comment by bjinwright** [comment]
This feature is now in the develop branch. I will close it when we release our first version later this week.

**Comment by blade2005** [comment]
Whats the progress on this?

**Comment by bjinwright** [comment]
It's done in the develop branch we are merging that today after we get the README docs finished and setup TravisCI. But if you can't wait use the develop branch.

**Comment by blade2005** [comment]
Ok. Awesome. Thanks.
