### ISSUE TITLE
Unable to locate credentials, does not login/authenticate

### ISSUE THREAD

**Issue by matayru** [capless/warrant#108]
botocore.exceptions.NoCredentialsError: Unable to locate credentials

warrant registers, but does not authenticate.

**Comment by dl-eric** [comment]
What was the fix?

**Comment by dpretty** [comment]
> What was the fix?

@dl-eric I saw this error as well, setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables worked for me.
