### ISSUE TITLE
python-jose not compatible with python 3.6

### ISSUE THREAD

**Issue by nueverest** [capless/warrant#31]
python-jose depends on pycrypto which is no longer maintained (3-4 years old).  This breaks compatibility with python 3.6 and people developing on windows machines. 

See issue here: https://github.com/mpdavis/python-jose/issues/41

pycryptodome is the preferred solution https://github.com/Legrandin/pycryptodome

This is making it hard for me to use your cool library.

It appears that check_token() and verify_token() depend on jose, and it is not immediately obvious how I can work around this.

**Comment by armicron** [comment]
Can we use [python-jose fork](https://github.com/nueverest/python-jose), until it will be fixed in the original repository?

**Comment by bjinwright** [comment]
Can we create a fork of the fork, rename it and push it to PyPi? If we try to add it to requirements.txt pointed to the git repo people that don't have git installed will not be able to install it. @nueverest Do you have a problem with that plan?

**Comment by armicron** [comment]
What is a name for the new package?
- [ ] python-capless-jose
- [ ] capless-jose
- [ ] python-jose-cryptodome

**Comment by bjinwright** [comment]
python-jose-cryptodome

**Comment by armicron** [comment]
https://github.com/capless/python-jose-cryptodome/pull/1
