### ISSUE TITLE
Anti-pattern - Use of default mutable arguments dict(), {} and []

### ISSUE THREAD

**Issue by nueverest** [capless/warrant#32]
> Passing mutable lists or dictionaries as default arguments to a function can have unforeseen consequences. Usually when a programmer uses a list or dictionary as the default argument to a function, the programmer wants the program to create a new list or dictionary every time that the function is called. However, this is not what Python does. The first time that the function is called, Python creates a persistent object for the list or dictionary. Every subsequent time the function is called, Python uses that same persistent object that was created from the first call to the function.

**Reference:**
https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html

**Comment by armicron** [comment]
The issue should be closed.
