### ISSUE TITLE
Less restrictive license?

### ISSUE THREAD

**Issue by whummer** [capless/warrant#38]
Thanks for making this awesome library available! Unfortunately, the GPL license under which the code is published is very restrictive, prohibiting users from actually being able to use `warrant` for certain scenarios.

Has this decision been made on purpose, or is there any chance to switch to a less restrictive license, like Apache 2 license [1], or MIT license [2], for example? Thanks!

[1] https://www.apache.org/licenses/LICENSE-2.0
[2] https://opensource.org/licenses/MIT

**Comment by pshendry** [comment]
Seconded, I started contributing before I noticed the license (dumb of me I know) but now I realize I can't use this. I've got nothing against GPL but for small utility libraries it's very restrictive. I'll probably see if I can make a wrapper around https://github.com/cocagne/pysrp

**Comment by balloob** [comment]
Fixed in 65160646ae0ef4418a15a9dcca240d5bd14516b7 🥂
