### ISSUE TITLE
 NoRegionError: No region specify  error is coming at the time of creation of cognito

### ISSUE THREAD

**Issue by rizwans-cuelogic** [capless/warrant#39]

**Comment by pshendry** [comment]
You've gotta tell Boto3 what region to use somehow (the region in which your Cognito user pool exists); either by passing it as an argument to `Cognito` or `AWSSRP` in this library, or setting the `AWS_DEFAULT_REGION` environment variable, or defining an AWS config file.

**Comment by rizwans-cuelogic** [comment]
I passed region name to cognito constructor but same exception is coming

**Comment by atwalsh04** [comment]
I am having the same issue as @rizwans-cuelogic. Passing the `user_pool_region` argument returns an error.

Example:
```
u = Cognito('your-user-pool-id', 'your-client-id', user_pool_region='us-east-1')
```
Returns this error:
```
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by faizans-cuelogic** [comment]
atwalsh04 your instance functions are working properly? because in cognito constructor code there is nothing given about AWS access  and secret key as parameter.

**Comment by atwalsh04** [comment]
@faizans-cuelogic Yes, the arguments for this are `access_key` and `secret_key`.

This line is from the Cognito constructor:
```
if access_key and secret_key:
    self.client = boto3.client('cognito-idp',
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name=self.user_pool_region
        )
else:
    self.client = boto3.client('cognito-idp')
```
If you do not pass these to the constructor, boto3 looks for AWS credentials as defined in the [boto3 Credentials Configuration](https://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials).
