### ISSUE TITLE
Feature-request: Support Client app w/generated secret

### ISSUE THREAD

**Issue by jonasao** [capless/warrant#44]
So far it seems that the authentication flow of warrant only supports AWS Cognito clients without generated secrets. (Like the official AWS Javascript APIs). 

It would have been great if warrant in the future also added support for AWS Cognito clients with generated secrets as well.

**Comment by armicron** [comment]
I am working on it [here](https://github.com/capless/warrant/tree/secret_hash)

**Comment by jonasao** [comment]
Great! Looking forward to testing it!

**Comment by armicron** [comment]
@bjinwright Can you create a new app client with a generated secret and add new environment variables to `Travis CI`?
![screenshot](https://user-images.githubusercontent.com/1076958/30875630-cc9efde0-a2fc-11e7-8573-755047dde08b.png)
Required env variables:
`COGNITO_APP_ID_WITH_SECRET`
`COGNITO_CLIENT_SECRET`
