### ISSUE TITLE
Question: Get user information, missing attributes

### ISSUE THREAD

**Issue by jonasao** [capless/warrant#47]
I am attempting to read user information from AWS Cognito using the get_user() method, but I am unsure if it works as expected.

What I am doing:
```
u = Cognito(.....)
user = u.get_user(attr_map={'given_name': 'firstname', 'family_name': 'lastname'})
``` 
I would have expected this method call to expose the values of 'firstname' and 'lastname' as separate properties, or as a single "data" property of the object "user", but unfortunately - no.

The values are only exposed via the user._data private property. Is this a bug, or am I missing something?

**Comment by armicron** [comment]
It seems that you need to swap keys with values in the `attr_map` dictionary. 
```python
>>> user_obj = user.get_user(attr_map={'firstname': 'given_name'})
>>> user_obj.given_name
'Jenkins'
```

**Comment by armicron** [comment]
What is in your `self._data`? What attribute are you trying to get?

**Comment by jonasao** [comment]
```self.data``` exposes the correct list of AWS Cognito attributes I am asking for, with the correct mapping of attribute names, according to the specifications mentioned above.

```
{
  'email': '....@gmail.com', 
  'lastname': 'Ols...', 'firstname': 'Jon.....',
  'custom:kit_app2': 'M24', 
  'custom:kit_app1': 'DM'
}
```
My problem is that all these values resides in a "private" object, not exposed via normal properties or "getter" methods.

**Comment by armicron** [comment]
It should be exposed as an attribute if it's in `self._dict` or `self._metadata`. Can you try to debug `__getattr__` method?
https://github.com/capless/warrant/blob/d109924e9e2a2cad34eb0f539f7491cef7585dbf/warrant/__init__.py#L64-L68

**Comment by jonasao** [comment]
I am able to get the values via the ```self.__getattr__()``` method, but this is still i private method. Shouldn't this method have been a public method of the user object?

**Comment by armicron** [comment]
`self.__getattr__(self, 'attribute_name')` is equal to `self.attribute_name`

[3.3.2. Customizing attribute access](https://docs.python.org/3/reference/datamodel.html?highlight=__getattr__#object.__getattr__)

**Comment by jonasao** [comment]
Ah, of course, my bad. Thanks!
