### ISSUE TITLE
Install failing on windows 10

### ISSUE THREAD

**Issue by flycast** [capless/warrant#64]
Using:

> pip install warrant

I get a bunch of output then:

>     ----------------------------------------
> Command "c:\users\eric\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Eric\\AppData\\Local\\Temp\\pip-build-41j7rx00\\pycryptodome\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Eric\AppData\Local\Temp\pip-slin_rdp-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Eric\AppData\Local\Temp\pip-build-41j7rx00\pycryptodome\
>

**Comment by armicron** [comment]
Hello. It's an issue with [pycryptodome](https://github.com/Legrandin/pycryptodome/issues) library. Try to run
`pip install pycryptodomex`, it's a precompiled version for Windows. If it wouldn't help try [this].(https://www.pycryptodome.org/en/latest/src/installation.html#windows-from-sources-python-3-5-and-newer)

**Comment by flycast** [comment]
Sorry for the lagging reply. I am now on a work computer with Windows 7 and same issue. I have installed pycryptodomex and that installs fine. The issue is that warrant does not seem to finish installing - it looks like the installer sees a newer version or different version of pycrptodome and tries to uninstall it and install the old version of pycryptodome. When this fails the warrant installation seems to roll back. 

My python script is still reporting that warrant is not installed.

**Comment by sillmnvg** [comment]
I had the same issue on win7, @armicron 's second link worked for me. Outline of the steps I used:
Download and install visual studio C/C++ compiler/built tools (using [this](http://landinghub.visualstudio.com/visual-cpp-build-tools) link)
run pip install pycryptodomex --no-use-wheel
re-run pip install warrant
